/*
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * Copyright (c) 2026 Cryptnox SA
 */
/* Auto-generated by tools/gen_card_img.py — do not edit. */

#ifndef CARD_IMG_H
#define CARD_IMG_H

#include "lvgl.h"

extern const lv_img_dsc_t card_img;

#endif /* CARD_IMG_H */
