/*
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * Copyright (c) 2026 Cryptnox SA
 */
/* Auto-generated by tools/gen_chain_icons.py - do not edit. */

#ifndef CHAIN_ICONS_H
#define CHAIN_ICONS_H

#include "lvgl.h"

extern const lv_img_dsc_t icon_usdc;
extern const lv_img_dsc_t icon_tron;
extern const lv_img_dsc_t icon_usdt;
extern const lv_img_dsc_t chip_tron;
extern const lv_img_dsc_t chip_eth;

#endif /* CHAIN_ICONS_H */
