/*
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * Copyright (c) 2026 Cryptnox SA
 */
/* Auto-generated by tools/gen_logo_mid.py — do not edit. */

#ifndef LOGO_MID_H
#define LOGO_MID_H

#include "lvgl.h"

extern const lv_img_dsc_t logo_mid;

#endif /* LOGO_MID_H */
