/*
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * Copyright (c) 2026 Cryptnox SA
 */
/* Auto-generated by tools/gen_logo.py — do not edit. */

#ifndef LOGO_SMALL_H
#define LOGO_SMALL_H

#include "lvgl.h"

extern const lv_img_dsc_t logo_small;

#endif /* LOGO_SMALL_H */
