/*
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * Copyright (c) 2026 Cryptnox SA
 */
/* Auto-generated by tools/gen_tap_icon.py from
 * assets/contactless-icon.svg - do not edit. */

#ifndef TAP_ICON_H
#define TAP_ICON_H

#include "lvgl.h"

/* 110x65 alpha mask; colour comes from the object's img_recolor. */
extern const lv_img_dsc_t tap_icon;

#endif /* TAP_ICON_H */
