/*
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * Copyright (c) 2026 Cryptnox SA
 */
/* Auto-generated by tools/gen_usdc_logo.py — do not edit. */

#ifndef USDC_LOGO_H
#define USDC_LOGO_H

#include "lvgl.h"

extern const lv_img_dsc_t usdc_logo;

#endif /* USDC_LOGO_H */
