#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (c) 2026 Cryptnox SA
"""Turn assets/cryptnox_card.png into the config portal's card illustration.

Inlined as a data URI rather than served from its own endpoint: the phone is on a
captive portal, and a second GET for a picture is a second thing that can hang —
the same reason the Cryptnox mark is inlined next to it in provision.cpp.

That only works because the file is small: the artwork is flat black with a gold
chip, so at twice the width the page ever draws it (15rem) and quantized to a
small palette it is ~3 KB of base64, against 24 KB for the original. Alpha is
kept, so the card's rounded corners stay transparent over either scheme.

Output: main/card_front.h.  Run from repo root:  python tools/gen_card_front.py
"""

import base64
import io

from PIL import Image

SRC    = "assets/cryptnox_card.png"
OUT_H  = "main/card_front.h"
WIDTH  = 480   # px, 2x the 15rem (240px) the page draws it at
COLORS = 64    # FASTOCTREE is the only quantizer that keeps RGBA

img = Image.open(SRC).convert("RGBA")
img = img.resize((WIDTH, round(img.height * WIDTH / img.width)), Image.LANCZOS)
img = img.quantize(colors=COLORS, method=Image.FASTOCTREE)

buf = io.BytesIO()
img.save(buf, "PNG", optimize=True)
png = buf.getvalue()
b64 = base64.b64encode(png).decode("ascii")

with open(OUT_H, "w", encoding="utf-8", newline="\n") as f:
    f.write("/*\n * SPDX-License-Identifier: LGPL-3.0-or-later\n"
            " * Copyright (c) 2026 Cryptnox SA\n */\n")
    f.write("/* Auto-generated by tools/gen_card_front.py — do not edit. */\n\n")
    f.write("#ifndef CARD_FRONT_H\n#define CARD_FRONT_H\n\n")
    f.write("/* The Cryptnox card front (assets/cryptnox_card.png), %dx%d, %d bytes\n"
            " * of PNG as a data URI for the config portal's <img class=cardart>. */\n"
            % (img.width, img.height, len(png)))
    f.write("#define CARD_FRONT_PNG_URI \\\n")
    f.write('    "data:image/png;base64," \\\n')
    for i in range(0, len(b64), 96):
        chunk = b64[i:i + 96]
        cont = " \\" if (i + 96) < len(b64) else ""
        f.write('    "%s"%s\n' % (chunk, cont))
    f.write("\n#endif /* CARD_FRONT_H */\n")

print("Wrote %s (%dx%d, %d bytes PNG, %d bytes base64)"
      % (OUT_H, img.width, img.height, len(png), len(b64)))

# Read the header back the way the C compiler will — concatenate its quoted
# chunks — and decode that. A mis-chunked URI is a picture that silently fails to
# appear on a phone, with nothing on the terminal to say so.
import re

with open(OUT_H, encoding="utf-8") as f:
    uri = "".join(re.findall(r'"((?:[^"\\]|\\.)*)"', f.read()))
assert uri.startswith("data:image/png;base64,"), uri[:40]
back = Image.open(io.BytesIO(base64.b64decode(uri.split(",", 1)[1])))
assert back.size == img.size, (back.size, img.size)
print("Round-trip OK (%s, %dx%d)" % (back.format, back.width, back.height))
