#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (c) 2026 Cryptnox SA
"""Convert Circle_USDC_Logo.svg.png into a small LVGL RGB565 image.

Flattened onto white (the UI background) and scaled down to sit next to the
amount on the keypad screen. Output: main/usdc_logo.c (+ .h).

Run from repo root:  python tools/gen_usdc_logo.py
"""

from PIL import Image

SRC    = "assets/Circle_USDC_Logo.svg.png"
OUT_C  = "main/usdc_logo.c"
OUT_H  = "main/usdc_logo.h"
TARGET = 30          # px, small badge beside the amount

img = Image.open(SRC).convert("RGBA")
bg  = Image.new("RGBA", img.size, (255, 255, 255, 255))   # flatten on white
img = Image.alpha_composite(bg, img).convert("RGB")
img.thumbnail((TARGET, TARGET), Image.LANCZOS)
w, h = img.size
px = img.load()

data = bytearray()
for y in range(h):
    for x in range(w):
        r, g, b = px[x, y]
        v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
        data.append(v & 0xFF)          # little-endian (matches lv_color_t, swap=0)
        data.append((v >> 8) & 0xFF)

with open(OUT_C, "w", newline="\n") as f:
    f.write("/*\n * SPDX-License-Identifier: LGPL-3.0-or-later\n"
            " * Copyright (c) 2026 Cryptnox SA\n */\n")
    f.write("/* Auto-generated by tools/gen_usdc_logo.py — do not edit. */\n\n")
    f.write('#include "lvgl.h"\n\n')
    f.write("static const uint8_t usdc_logo_map[] = {\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("    " + ",".join("0x%02X" % b for b in chunk) + ",\n")
    f.write("};\n\n")
    f.write("const lv_img_dsc_t usdc_logo = {\n")
    f.write("    .header = {\n")
    f.write("        .cf = LV_IMG_CF_TRUE_COLOR,\n")
    f.write("        .always_zero = 0,\n")
    f.write("        .reserved = 0,\n")
    f.write("        .w = %d,\n" % w)
    f.write("        .h = %d,\n" % h)
    f.write("    },\n")
    f.write("    .data_size = %d,\n" % len(data))
    f.write("    .data = usdc_logo_map,\n")
    f.write("};\n")

with open(OUT_H, "w", newline="\n") as f:
    f.write("/*\n * SPDX-License-Identifier: LGPL-3.0-or-later\n"
            " * Copyright (c) 2026 Cryptnox SA\n */\n")
    f.write("/* Auto-generated by tools/gen_usdc_logo.py — do not edit. */\n\n")
    f.write("#ifndef USDC_LOGO_H\n#define USDC_LOGO_H\n\n")
    f.write('#include "lvgl.h"\n\n')
    f.write("extern const lv_img_dsc_t usdc_logo;\n\n")
    f.write("#endif /* USDC_LOGO_H */\n")

print("Wrote %s (%dx%d, %d bytes)" % (OUT_C, w, h, len(data)))
