#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (c) 2026 Cryptnox SA
"""Convert logo.svg into an LVGL TRUE_COLOR (RGB565) image for the splash.

The source is a white 'C' monogram on a black disc (with transparent corners).
We rasterise it onto a FULL black rectangle (bg=black flattens the transparent
corners), so the splash shows a uniform black background — no visible circle —
with the white strokes. Rendered as greyscale RGB565 (grey anti-aliased edges).
Output: main/logo_img.c (+ .h).

Run from repo root:  python tools/gen_logo.py
"""

from PIL import Image, ImageOps
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPM

SRC    = "assets/logo.svg"
OUT_C  = "main/logo_img.c"
OUT_H  = "main/logo_img.h"
TARGET = 120          # bounding box (px) on the 320x240 splash

drawing = svg2rlg(SRC)
# bg=0x000000 fills the whole canvas black, flattening the SVG's transparent
# corners so the result is a solid black rectangle, not a disc. Rendered at the
# SVG's native size (~461px) then downscaled for clean anti-aliasing.
img = renderPM.drawToPIL(drawing, bg=0x000000).convert("L")

# Crop to the white glyph and re-centre it in a square canvas — the 'C' is open
# on the right, so its geometric centre differs from its visual centre; this
# guarantees the strokes sit dead-centre on the splash.
bbox = img.getbbox()            # bounding box of the non-black (white) pixels
if bbox is not None:
    glyph = img.crop(bbox)
    side  = max(glyph.size) + max(glyph.size) // 8   # small breathing margin
    img   = Image.new("L", (side, side), 0)          # black square
    img.paste(glyph, ((side - glyph.width) // 2, (side - glyph.height) // 2))

img.thumbnail((TARGET, TARGET), Image.LANCZOS)

# Invert: the splash uses a WHITE background, so we want a black 'C' on white
# (luminance flip of the white-on-black render).
img = ImageOps.invert(img)

w, h = img.size
px = img.load()


def rgb565_le(v):
    # greyscale: r=g=b=v
    val = ((v >> 3) << 11) | ((v >> 2) << 5) | (v >> 3)
    return val & 0xFF, (val >> 8) & 0xFF   # little-endian (matches lv_color_t, swap=0)


data = bytearray()
for y in range(h):
    for x in range(w):
        lo, hi = rgb565_le(px[x, y])
        data.append(lo)
        data.append(hi)

with open(OUT_C, "w", newline="\n") as f:
    f.write("/*\n * SPDX-License-Identifier: LGPL-3.0-or-later\n"
            " * Copyright (c) 2026 Cryptnox SA\n */\n")
    f.write("/* Auto-generated by tools/gen_logo.py from logo.svg — do not edit. */\n\n")
    f.write('#include "lvgl.h"\n\n')
    f.write("static const uint8_t logo_map[] = {\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("    " + ",".join("0x%02X" % b for b in chunk) + ",\n")
    f.write("};\n\n")
    f.write("const lv_img_dsc_t logo_img = {\n")
    f.write("    .header = {\n")
    f.write("        .cf = LV_IMG_CF_TRUE_COLOR,\n")
    f.write("        .always_zero = 0,\n")
    f.write("        .reserved = 0,\n")
    f.write("        .w = %d,\n" % w)
    f.write("        .h = %d,\n" % h)
    f.write("    },\n")
    f.write("    .data_size = %d,\n" % len(data))
    f.write("    .data = logo_map,\n")
    f.write("};\n")

with open(OUT_H, "w", newline="\n") as f:
    f.write("/*\n * SPDX-License-Identifier: LGPL-3.0-or-later\n"
            " * Copyright (c) 2026 Cryptnox SA\n */\n")
    f.write("/* Auto-generated by tools/gen_logo.py — do not edit. */\n\n")
    f.write("#ifndef LOGO_IMG_H\n#define LOGO_IMG_H\n\n")
    f.write('#include "lvgl.h"\n\n')
    f.write("extern const lv_img_dsc_t logo_img;\n\n")
    f.write("#endif /* LOGO_IMG_H */\n")

print("Wrote %s (%dx%d, %d bytes of pixel data)" % (OUT_C, w, h, len(data)))
