#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (c) 2026 Cryptnox SA
"""Convert carte.png into a small LVGL RGB565 image.

Flattened onto white (the UI background) and scaled down to sit next to the
amount on the keypad screen. Output: main/card_img.c (+ .h).

Run from repo root:  python tools/gen_card_img.py
"""

from PIL import Image
from rgb565 import rgb565_le_dithered

SRC    = "assets/carte.png"
OUT_C  = "main/card_img.c"
OUT_H  = "main/card_img.h"
TARGET = 96           # px, card icon on the "tap card" screen

img = Image.open(SRC).convert("RGBA")
bg  = Image.new("RGBA", img.size, (255, 255, 255, 255))   # flatten on white
img = Image.alpha_composite(bg, img).convert("RGB")
img.thumbnail((TARGET, TARGET), Image.LANCZOS)
w, h = img.size

data = rgb565_le_dithered(img)         # rounded + Floyd-Steinberg, no banding

with open(OUT_C, "w", newline="\n") as f:
    f.write("/*\n * SPDX-License-Identifier: LGPL-3.0-or-later\n"
            " * Copyright (c) 2026 Cryptnox SA\n */\n")
    f.write("/* Auto-generated by tools/gen_card_img.py — do not edit. */\n\n")
    f.write('#include "lvgl.h"\n\n')
    f.write("static const uint8_t card_img_map[] = {\n")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        f.write("    " + ",".join("0x%02X" % b for b in chunk) + ",\n")
    f.write("};\n\n")
    f.write("const lv_img_dsc_t card_img = {\n")
    f.write("    .header = {\n")
    f.write("        .cf = LV_IMG_CF_TRUE_COLOR,\n")
    f.write("        .always_zero = 0,\n")
    f.write("        .reserved = 0,\n")
    f.write("        .w = %d,\n" % w)
    f.write("        .h = %d,\n" % h)
    f.write("    },\n")
    f.write("    .data_size = %d,\n" % len(data))
    f.write("    .data = card_img_map,\n")
    f.write("};\n")

with open(OUT_H, "w", newline="\n") as f:
    f.write("/*\n * SPDX-License-Identifier: LGPL-3.0-or-later\n"
            " * Copyright (c) 2026 Cryptnox SA\n */\n")
    f.write("/* Auto-generated by tools/gen_card_img.py — do not edit. */\n\n")
    f.write("#ifndef CARD_IMG_H\n#define CARD_IMG_H\n\n")
    f.write('#include "lvgl.h"\n\n')
    f.write("extern const lv_img_dsc_t card_img;\n\n")
    f.write("#endif /* CARD_IMG_H */\n")

print("Wrote %s (%dx%d, %d bytes)" % (OUT_C, w, h, len(data)))
