#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (c) 2026 Cryptnox SA
"""Draw the "tap your card" mark: a payment card and the NFC waves.

ORIGINAL GEOMETRY, drawn here from rectangles and arcs. No stock file is traced
or vendored — a card-and-waves composition is generic, but any particular
drawing of it is somebody's copyright, and a stock licence is not something
firmware should be carrying around. Everything below is authored in this
script, which is why the source is the artwork and there is no asset in
assets/ for this one.

A hand was drawn here first and taken out again: three fingers and a palm is
more hand than 96 pixels hold beside a card and three waves, and every version
of it read as a blob. Two objects is what this size supports.

Trademark, separately from copyright: EMVCo's Contactless Indicator is four bare
arcs on their own. This is a card and three waves — the card is the difference,
and it is not that mark nor trying to be.

Output is LV_IMG_CF_ALPHA_8BIT — one alpha byte per pixel, 9 KB at 96x96, with
the colour coming from the object's img_recolor style at draw time. That is the
right format for single-colour line art: a TRUE_COLOR_ALPHA version of the same
thing is three times the size to say the same thing three times over. LVGL draws
this format through a fast path that does NOT support angle/zoom, so the card's
tilt is baked in here rather than applied on the panel.

Run from repo root:  python tools/gen_tap_icon.py [--preview]
"""

import sys

from PIL import Image, ImageDraw

OUT_C = "main/tap_icon.c"
OUT_H = "main/tap_icon.h"
PX    = 96     # the box ui.cpp reserves for it (TAP_MARK_SZ)
SS    = 6      # supersampling, downsampled at the end for clean edges

INK   = (0, 0, 0, 255)
ERASE = (0, 0, 0, 0)
W     = 4      # stroke, in final pixels


def s(v):
    """Scale a 1x coordinate into the supersampled canvas."""
    return int(round(v * SS))


def capsule(d, cx, cy, length, thick, fill, outline=None, width=0):
    """A rounded bar centred on (cx, cy), horizontal. Rotation is done by the
    caller drawing onto its own layer and rotating that."""
    box = [s(cx - length / 2), s(cy - thick / 2),
           s(cx + length / 2), s(cy + thick / 2)]
    d.rounded_rectangle(box, radius=s(thick / 2), fill=fill,
                        outline=outline, width=width)


def layer():
    img = Image.new("RGBA", (PX * SS, PX * SS), ERASE)
    return img, ImageDraw.Draw(img)


def rotated(img, deg):
    """Rotate about the canvas centre, keeping the same box."""
    return img.rotate(deg, resample=Image.BICUBIC, expand=False)


def build():
    base, d = layer()

    # ── The waves. Three arcs about a centre off the left edge, opening east
    # toward the card, so they read as reaching it rather than decorating it.
    for r in (15, 23, 31):
        cx, cy = 2, 53
        d.arc([s(cx - r), s(cy - r), s(cx + r), s(cy + r)],
              start=-48, end=48, fill=INK, width=s(W))

    # ── The card, drawn square on its own layer and then tilted. Outlined, not
    # filled: the whole mark is one colour, and a solid card would be a blob.
    card, cd = layer()
    cw, ch = 38, 50
    ccx, ccy = 64, 53
    cd.rounded_rectangle([s(ccx - cw / 2), s(ccy - ch / 2),
                          s(ccx + cw / 2), s(ccy + ch / 2)],
                         radius=s(6), fill=ERASE, outline=INK, width=s(W))
    # The chip. One detail is what separates a card from a door.
    cd.rounded_rectangle([s(ccx - 12), s(ccy - 16), s(ccx - 1), s(ccy - 8)],
                         radius=s(2), fill=INK)
    # A magnetic-stripe-ish band low on the face, for the same reason.
    cd.rounded_rectangle([s(ccx - 12), s(ccy + 6), s(ccx + 8), s(ccy + 10)],
                         radius=s(2), fill=INK)
    base.alpha_composite(rotated(card, 16))

    # Downsample: the supersampling is the whole antialiasing strategy.
    return base.resize((PX, PX), Image.LANCZOS)


img = build()

if "--preview" in sys.argv:
    # On white, at 4x, which is how it will be seen — line art that survives
    # only on a grey checkerboard is line art that is too thin.
    bg = Image.new("RGBA", (PX, PX), (255, 255, 255, 255))
    Image.alpha_composite(bg, img).resize(
        (PX * 4, PX * 4), Image.NEAREST).save("build/preview_tap_icon.png")
    print("Wrote build/preview_tap_icon.png")

data = bytes(img.getchannel("A").tobytes())

HDR = ("/*\n * SPDX-License-Identifier: LGPL-3.0-or-later\n"
       " * Copyright (c) 2026 Cryptnox SA\n */\n"
       "/* Auto-generated by tools/gen_tap_icon.py - do not edit. */\n\n")

with open(OUT_C, "w", newline="\n") as f:
    f.write(HDR)
    f.write('#include "lvgl.h"\n\n')
    f.write("static const uint8_t tap_icon_map[] = {\n")
    for i in range(0, len(data), 15):
        f.write("    " + ",".join("0x%02X" % b for b in data[i:i + 15]) + ",\n")
    f.write("};\n\n")
    f.write("const lv_img_dsc_t tap_icon = {\n")
    f.write("    .header = {\n"
            "        .cf = LV_IMG_CF_ALPHA_8BIT,\n"
            "        .always_zero = 0,\n"
            "        .reserved = 0,\n")
    f.write("        .w = %d,\n        .h = %d,\n    },\n" % (PX, PX))
    f.write("    .data_size = %d,\n" % len(data))
    f.write("    .data = tap_icon_map,\n};\n")

with open(OUT_H, "w", newline="\n") as f:
    f.write(HDR)
    f.write("#ifndef TAP_ICON_H\n#define TAP_ICON_H\n\n")
    f.write('#include "lvgl.h"\n\n')
    f.write("/* %dx%d alpha mask; colour comes from the object's img_recolor. */\n"
            % (PX, PX))
    f.write("extern const lv_img_dsc_t tap_icon;\n")
    f.write("\n#endif /* TAP_ICON_H */\n")

print("Wrote %s: %dx%d (%d B)" % (OUT_C, PX, PX, len(data)))
