#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (c) 2026 Cryptnox SA
"""Subset the portal's four faces from assets/fonts/ into main/portal_fonts.h.

The config portal is opened on a phone joined to the terminal's own access
point, with no route to a font CDN — so the faces travel inside the page, as
WOFF2 data URIs in @font-face rules, the way card_front.h carries the card
picture. Subset to the characters the page can print (ASCII plus the handful of
typographic marks it spells as entities) and stripped of hinting, which phones
ignore: 6-12 KB a face instead of ~130.

Plus Jakarta Sans SemiBold for the brand, headings and buttons; Inter Regular,
Medium and SemiBold (for <b>) for everything read. Both OFL 1.1, licences
next to the TTFs.

Needs fonttools and brotli (pip install fonttools brotli). From the repo root:
    python tools/gen_portal_fonts.py
"""
import base64
import io
import re

from fontTools import subset
from fontTools.ttLib import TTFont

OUT_H = "main/portal_fonts.h"
# family, weight, file
FACES = [
    ("Plus Jakarta Sans", 600, "assets/fonts/PlusJakartaSans-SemiBold.ttf"),
    ("Inter",             400, "assets/fonts/Inter-Regular.ttf"),
    ("Inter",             500, "assets/fonts/Inter-Medium.ttf"),
    ("Inter",             600, "assets/fonts/Inter-SemiBold.ttf"),
]
UNICODES = list(range(0x20, 0x7F)) + [0xA0, 0xB7, 0x2013, 0x2014, 0x2018, 0x2019,
                                      0x201C, 0x201D, 0x2022, 0x2026, 0x2192]


def woff2(path):
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.hinting = False
    opts.desubroutinize = True
    opts.name_IDs = []            # the page never shows the font's own name
    font = TTFont(path)
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=UNICODES)
    sub.subset(font)
    buf = io.BytesIO()
    subset.save_font(font, buf, opts)
    return buf.getvalue()


rules, sizes = [], []
for family, weight, path in FACES:
    data = woff2(path)
    sizes.append((family, weight, len(data)))
    rules.append("@font-face{font-family:'%s';font-weight:%d;font-display:swap;"
                 "src:url(data:font/woff2;base64,%s) format('woff2')}"
                 % (family, weight, base64.b64encode(data).decode("ascii")))
css = "".join(rules)

with open(OUT_H, "w", encoding="utf-8", newline="\n") as f:
    f.write("/*\n * SPDX-License-Identifier: LGPL-3.0-or-later\n"
            " * Copyright (c) 2026 Cryptnox SA\n */\n")
    f.write("/* Auto-generated by tools/gen_portal_fonts.py — do not edit. */\n\n")
    f.write("#ifndef PORTAL_FONTS_H\n#define PORTAL_FONTS_H\n\n")
    f.write("/* @font-face rules for the config portal, WOFF2 subsets as data URIs:\n")
    for family, weight, n in sizes:
        f.write(" *   %s %d, %d bytes\n" % (family, weight, n))
    f.write(" * Fonts under the SIL Open Font License 1.1 — assets/fonts/. */\n")
    f.write("#define PORTAL_FONTS_CSS \\\n")
    for i in range(0, len(css), 96):
        cont = " \\" if (i + 96) < len(css) else ""
        f.write('    "%s"%s\n' % (css[i:i + 96], cont))
    f.write("\n#endif /* PORTAL_FONTS_H */\n")

# Read it back the way the compiler will and check every face decodes.
text = open(OUT_H, encoding="utf-8").read()
joined = "".join(re.findall(r'"([^"]*)"', text.split("#define PORTAL_FONTS_CSS", 1)[1]))
assert joined == css, "chunking changed the CSS"
for b64 in re.findall(r"base64,([A-Za-z0-9+/=]+)\)", joined):
    TTFont(io.BytesIO(base64.b64decode(b64)))
print("Wrote %s: %s" % (OUT_H, ", ".join("%s %d %d B" % s for s in sizes)))
